version: '3'
services:
    mariadb:
      image: 'mariadb:latest'
      restart: always
      environment:
        - MARIADB_ROOT_USER=root
        - MARIADB_ROOT_PASSWORD=mariadb_rootpassword
        - MARIADB_DATABASE=mariadb
        - MARIADB_USER=mariadb
        - MARIADB_PASSWORD=mariadb_password
        - MYSQL_ROOT_USER=root
        - MYSQL_ROOT_PASSWORD=mariadb_rootpassword
        - MYSQL_DATABASE=mariadb
        - MYSQL_USER=mariadb
        - MYSQL_PASSWORD=mariadb_password
    postgres:
      image: 'postgres:alpine'
      restart: always
      environment:
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
    redis:
      image: 'redis:alpine'
      restart: always
    nginx:
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      restart: always
      ports:
        - '3050:80'
      expose:
        - '80'
    api:
      build:
        dockerfile: Dockerfile.dev
        context: ./api
      volumes:
        #Don't touch /app/node_modules
        - /app/node_modules       
        #Sinchronyze server to app
        - ./api:/app
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
        - MARIADBDATABASE=mariadb
        - MARIADBUSER=mariadb
        - MARIADBDPASSWORD=mariadb_password
        - MARIADBHOST=mariadb
        - MARIADBPORT=3306
        - MARIADCONNECTIONLIMIT=5
      links:
        - postgres
        - mariadb
        - nginx
    client:
      build:
        dockerfile: Dockerfile.dev
        context: ./client
      volumes:
        #Don't touch /app/node_modules
        - /app/node_modules       
        #Sinchronyze server to app
        - ./client:/app
      links:
        - postgres
        - mariadb
        - nginx
    worker:
      build:
        dockerfile: Dockerfile.dev
        context: ./worker
      volumes:
        #Don't touch /app/node_modules
        - /app/node_modules       
        #Sinchronyze server to app
        - ./worker:/app
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      links:
        - postgres
        - mariadb
        - nginx
